#### Examples 1

!pip install randomuser
!pip install pandas

In [2]:
from randomuser import RandomUser
import pandas as pd

In [3]:
r = RandomUser()

In [4]:
some_list = r.generate_users(10)

In [5]:
some_list

[<randomuser.RandomUser at 0x23f570543c8>,
 <randomuser.RandomUser at 0x23f57054408>,
 <randomuser.RandomUser at 0x23f57054448>,
 <randomuser.RandomUser at 0x23f57054488>,
 <randomuser.RandomUser at 0x23f570544c8>,
 <randomuser.RandomUser at 0x23f57054548>,
 <randomuser.RandomUser at 0x23f57054588>,
 <randomuser.RandomUser at 0x23f570545c8>,
 <randomuser.RandomUser at 0x23f57054608>,
 <randomuser.RandomUser at 0x23f57054508>]

In [6]:
name = r.get_full_name()

In [8]:
for user in some_list:
    print (user.get_full_name(),"   ",user.get_email())

Christian Christensen     christian.christensen@example.com
Zachary Carlson     zachary.carlson@example.com
Till Leclercq     till.leclercq@example.com
Eva Wheeler     eva.wheeler@example.com
Amir Menard     amir.menard@example.com
Oliver King     oliver.king@example.com
Alexis Howell     alexis.howell@example.com
Ellie Clarke     ellie.clarke@example.com
Mathilde Nielsen     mathilde.nielsen@example.com
Keith Nelson     keith.nelson@example.com

In [10]:
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/men/93.jpg
https://randomuser.me/api/portraits/men/99.jpg
https://randomuser.me/api/portraits/women/21.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/men/12.jpg
https://randomuser.me/api/portraits/women/75.jpg
https://randomuser.me/api/portraits/women/59.jpg
https://randomuser.me/api/portraits/women/76.jpg
https://randomuser.me/api/portraits/men/71.jpg

In [ ]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [12]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Jonas Moraes,male,Itajaí,Goiás,jonas.moraes@example.com,1991-07-23T17:22:29.797Z,https://randomuser.me/api/portraits/men/1.jpg
1,Horst Kohn,male,Filderstadt,Schleswig-Holstein,horst.kohn@example.com,1994-03-12T00:34:11.634Z,https://randomuser.me/api/portraits/men/66.jpg
2,Franklin Wade,male,Exeter,South Glamorgan,franklin.wade@example.com,1995-04-15T02:15:37.913Z,https://randomuser.me/api/portraits/men/82.jpg
3,Heather Ross,female,Busselton,Queensland,heather.ross@example.com,1946-04-25T23:10:14.013Z,https://randomuser.me/api/portraits/women/87.jpg
4,Julia Cortes,female,Oviedo,Comunidad Valenciana,julia.cortes@example.com,1995-09-08T05:02:38.353Z,https://randomuser.me/api/portraits/women/80.jpg
5,Diego Adam,male,Grenoble,Marne,diego.adam@example.com,1962-03-11T14:58:07.899Z,https://randomuser.me/api/portraits/men/84.jpg
6,Gavin Carr,male,Cincinnati,Colorado,gavin.carr@example.com,1995-03-11T03:11:54.143Z,https://randomuser.me/api/portraits/men/24.jpg
7,Carlos Fjellheim,male,Hestvika,Vestfold,carlos.fjellheim@example.com,1986-10-06T00:26:22.682Z,https://randomuser.me/api/portraits/men/23.jpg
8,Guy Mason,male,Edinburgh,Cheshire,guy.mason@example.com,1986-01-01T01:40:44.178Z,https://randomuser.me/api/portraits/men/10.jpg
9,Hans-J. Altmeyer,male,Voerde (Niederrhein),Thüringen,hans-j..altmeyer@example.com,1976-10-28T00:19:23.088Z,https://randomuser.me/api/portraits/men/88.jpg

In [13]:
df1 = pd.DataFrame(get_users())

In [14]:
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Orlando Olivier,male,Villars-Epeney,Uri,orlando.olivier@example.com,1967-11-14T22:36:00.989Z,https://randomuser.me/api/portraits/men/79.jpg
1,Paulus De Rijcke,male,Hagestein,Drenthe,paulus.derijcke@example.com,1954-02-05T13:01:34.475Z,https://randomuser.me/api/portraits/men/52.jpg
2,Mesaque Nascimento,male,Araguaína,Rondônia,mesaque.nascimento@example.com,1979-05-17T13:38:04.283Z,https://randomuser.me/api/portraits/men/26.jpg
3,Amy Berhe,female,Vollen,Telemark,amy.berhe@example.com,1992-07-15T00:37:09.402Z,https://randomuser.me/api/portraits/women/28.jpg
4,Lambert Kögler,male,Kierspe,Rheinland-Pfalz,lambert.kogler@example.com,1979-05-22T08:27:12.552Z,https://randomuser.me/api/portraits/men/27.jpg
5,Daisy Nogueira,female,Camaragibe,Amapá,daisy.nogueira@example.com,1952-02-15T12:50:19.519Z,https://randomuser.me/api/portraits/women/10.jpg
6,Keli Peixoto,female,Colatina,Rio de Janeiro,keli.peixoto@example.com,1960-05-24T19:04:11.836Z,https://randomuser.me/api/portraits/women/23.jpg
7,Nathan Chow,male,Selkirk,Manitoba,nathan.chow@example.com,1944-09-08T13:11:23.313Z,https://randomuser.me/api/portraits/men/93.jpg
8,Juliette Mercier,female,Roubaix,Moselle,juliette.mercier@example.com,1968-02-26T23:18:49.475Z,https://randomuser.me/api/portraits/women/69.jpg
9,Eddie White,male,Lewisville,Kentucky,eddie.white@example.com,1985-04-11T06:00:51.944Z,https://randomuser.me/api/portraits/men/42.jpg

###  Fruityvice API Example

In [15]:
import requests
import json

In [16]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")

In [17]:
results = json.loads(data.text)

In [22]:
df2= pd.DataFrame(results)

In [23]:
df2

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

In [25]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

### Another Example

In [27]:
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")

In [28]:
data2

In [29]:
results2 = json.loads(data2.text)